export const demoDesigns = {
  designs: {
    "tour-1": {
      tree: [
        "div",
        "  (",
        "    style",
        "    width: 100%; height: 100%;",
        "    =",
        "h1",
        "(",
        "textContent",
        " Welcome to Unide!",
        "=",
        ")",
        "p",
        "(",
        "textContent",
        "This application is a visual designer for Vaadin 14+ that eports to plain Java.",
        "=",
        ")",
        "p",
        "(",
        "textContent",
        '\tThe things you see here are all part of the design. You can drag and drop them to reorder things. Writing another name to the "Design name" box above and pressing "Save Design" saves a copy of the design under the new name. It\'s also possible to insert new elements by dragging and dropping them from the palette on the right. Dragging and dropping is also possible between the outline on the top right and the paper where the design is visible.',
        "=",
        ")",
        "p",
        "(",
        "textContent",
        "\tThere are many Vaadin Components available in the palete with more to come. Here are a few:",
        "=",
        ")",
        "ul",
        "(",
        "li",
        "(",
        "textContent",
        "\tButtons:",
        "=",
        "vaadin-button",
        "(",
        "textContent",
        "\tClicking is what I do",
        "=",
        "theme",
        "\tprimary",
        "=",
        ")",
        ")",
        "li",
        "(",
        "textContent",
        "\tFields",
        "=",
        "vaadin-date-picker",
        "(",
        ")",
        ")",
        "li",
        "(",
        "textContent",
        "\tMaybe even a grid?",
        "=",
        "style",
        " height:10rem; width: 30rem",
        "=",
        "unide-grid",
        "(",
        "style",
        "\theight:100px;",
        "=",
        "columnCaptions",
        '\t[{"name":"Question","path":"question"},{"name":"Answer","path":"answer"}]',
        "=",
        "items",
        '\t[{"question":"Does this make sense?", "answer":"Maybe."}, {"question":"Are you sure?", "answer":"Time will tell."}]',
        "=",
        ")",
        ")",
        ")",
        "vaadin-button",
        "(",
        "textContent",
        " Adding navigation is possible. Double click here to go the next page!",
        "=",
        "theme",
        " primary",
        "=",
        "targetRoute",
        " tour-2",
        "=",
        ")",
        "  )"
      ],
      css: "h1 {\n  color: black;\n}\n"
    },
    "tour-2": {
      tree: [
        "div",
        "  (",
        "    style",
        "    width: 100%; height: 100%;",
        "    =",
        "h1",
        "(",
        "textContent",
        "\tWelcome to page 2 of the tour!",
        "=",
        "targetRoute",
        " tour-1",
        "=",
        ")",
        "span",
        "(",
        "textContent",
        ' Nothing much here yet. Double click on the header text to get back to page 1. Or just select it from the "Load" dropdown.',
        "=",
        ")",
        "p",
        "(",
        "textContent",
        ' Except... Exporting the design can be done by choosing the target from the "Export" dropdown above, and then clicking on "Export". Java exports as a Java project that can be built with maven. The raw export produces a file that can be imported by first clicking on "Choose File" and the "Import Raw". That replaces the complete project, so be careful!',
        "=",
        ")",
        "p",
        "(",
        "textContent",
        ' One more thing. The exported project can be built and run with "mvn package" followed by "mvn jetty:run".',
        "=",
        ")",
        "  )"
      ],
      css: ""
    }
  },
  settings: { packageName: "unide.app", exportFormat: "Java" }
};
