export let demoDesigns = {
  "login-view": [
    "div",
    "  (",
    "style",
    "\twidth: 100%; height: 100%;display:flex;justify-content:center;flex-direction:column;background:url(sky.jpg)",
    "=",
    "div",
    "  (",
    "style",
    "\tbackground-color: #fff;color:black;width:60%; margin-left:20%; border-radius:20px; border:3px solid black;",
    "=",
    "h1",
    "(",
    "textContent",
    " Login",
    "=",
    ")",
    "div",
    "(",
    "style",
    "\twidth: 100%; display:grid;grid-template-columns: 10em auto; padding: 1em; box-sizing:border-box;color:black;",
    "=",
    "span",
    "(",
    "textContent",
    " name",
    "=",
    ")",
    "vaadin-text-field",
    "(",
    ")",
    "span",
    "(",
    "textContent",
    " password",
    "=",
    ")",
    "vaadin-password-field",
    "(",
    ")",
    "span",
    "(",
    ")",
    "span",
    "(",
    "style",
    " display:flex",
    "=",
    "vaadin-button",
    "(",
    "textContent",
    "\tlogin",
    "=",
    "targetRoute",
    "\tmain-view",
    "=",
    "theme",
    " primary",
    "=",
    ")",
    "vaadin-button",
    "(",
    "textContent",
    "\tregister",
    "=",
    "style",
    "\tmargin-left:1rem;",
    "=",
    "targetRoute",
    " registration-view",
    "=",
    ")",
    ")",
    ")",
    "  )",
    "  )"
  ],
  "main-view": [
    "div",
    "(",
    "style",
    " height:100%;width:100%;background-color:white;",
    "=",
    "vaadin-tabs",
    "(",
    "vaadin-tab",
    "(",
    "textContent",
    " Main",
    "=",
    ")",
    "vaadin-tab",
    "(",
    "textContent",
    "\tOther",
    "=",
    "targetRoute",
    " other-view",
    "=",
    ")",
    ")",
    "vaadin-grid",
    "(",
    "items",
    "\t[{'name': 'John', 'surname': 'Lennon', 'role': 'singer'}, {'name': 'Ringo', 'surname': 'Starr', 'role': 'drums'}]",
    "=",
    ")",
    ")"
  ],
  "registration-view": [
    "div",
    "  (",
    "    style",
    "    width: 100%; height: 100%;",
    "    =",
    "div",
    "  (",
    "style",
    "\twidth: 100%; height: 100%;display:flex;justify-content:center;flex-direction:column;background:url(sky.jpg)",
    "=",
    "div",
    "  (",
    "style",
    "\tbackground-color: #fff;color:black;width:60%; margin-left:20%; border-radius:20px; border:3px solid black;",
    "=",
    "h1",
    "(",
    "textContent",
    "\tRegister a new user",
    "=",
    ")",
    "div",
    "(",
    "style",
    "\twidth: 100%; display:grid;grid-template-columns: 10em auto; padding: 1em; box-sizing:border-box;color:black;",
    "=",
    "span",
    "(",
    "textContent",
    " name",
    "=",
    ")",
    "vaadin-text-field",
    "(",
    ")",
    "span",
    "(",
    "textContent",
    " password",
    "=",
    ")",
    "vaadin-password-field",
    "(",
    ")",
    "span",
    "(",
    "textContent",
    " Repeat password",
    "=",
    ")",
    "vaadin-password-field",
    "(",
    ")",
    "span",
    "(",
    ")",
    "span",
    "(",
    "style",
    " display:flex",
    "=",
    "vaadin-button",
    "(",
    "textContent",
    "\tRegister",
    "=",
    "targetRoute",
    "\tlogin-view",
    "=",
    "theme",
    "\tprimary",
    "=",
    ")",
    "vaadin-button",
    "(",
    "textContent",
    "\tCancel",
    "=",
    "style",
    "\tmargin-left:1rem;",
    "=",
    "targetRoute",
    " login-view",
    "=",
    ")",
    ")",
    ")",
    "  )",
    "  )",
    "  )"
  ],
  "other-view": [
    "div",
    "  (",
    "    style",
    "    width: 100%; height: 100%;",
    "    =",
    "div",
    "(",
    "style",
    " height:100%;width:100%;background-color:white;",
    "=",
    "vaadin-tabs",
    "(",
    "vaadin-tab",
    "(",
    "textContent",
    "\tMain",
    "=",
    "targetRoute",
    " main-view",
    "=",
    ")",
    "vaadin-tab",
    "(",
    "textContent",
    "\tOther",
    "=",
    "targetRoute",
    " other-view",
    "=",
    ")",
    ")",
    "vaadin-form-layout",
    "(",
    ")",
    ")",
    "  )"
  ]
};
